language: R
cache: packages
latex: false
pandoc: false
fortran: false

matrix:
  include:
    - dist: trusty
    - dist: xenial
    - os: osx
      osx_image: xcode10.1
      warnings_are_errors: false
    - os: osx
      osx_image: xcode9.0
      warnings_are_errors: false


after_success:
    - Rscript -e 'covr::codecov(quiet = FALSE)'
