language: R
cache: packages
latex: false
pandoc: false
fortran: false

matrix:
  include:
    - dist: trusty
    - dist: xenial
    - os: osx
    - os: osx
      osx_image: xcode7.3


after_success:
    - Rscript -e 'covr::codecov(quiet = FALSE)'
